---
title: Checklist for R package submission to CRAN
author: Kamil Wais
date: '2015-04-21'
slug: checklist-for-r-package-submission-to-cran
categories:
  - programming
tags:
  - R
  - programming
  - software
---

## Version: 1.2

The last update of this post: `r Sys.Date()`.

Below is a checklist that I wrote for my own purposes. I helps me to be sure that I did what I should have done before release a new version of R package to CRAN. Maybe it will also help others.

1. __See what new Hadley recommends__:   
(http://r-pkgs.had.co.nz/release.html).
1. __Update R & packages__:
    1. R
    1. all packages
    1. RStudio (stable or preview version).
1. __Update your package__:
    1. Check unit tests.
    1. Update vignettes.
    1. Check reverse dependencies.
        1. If devtools functions don’t work use:   
        tools::dependsOnPkgs()
    1. Import undefined globals in the NAMESPACE file   
    (generated automatically by roxygen2)
1. __Update README.md file__:
    1. Make change in README.Rmd.
    1. Knit the Rmd into md.
1. __Run a R CMD check locally with ‘–as-cran‘ option__.
    1. If you got an error regarding qpdf missing, check:
        1. View(Sys.getenv(“PATH”) )
        1. Sys.which(Sys.getenv(“R_QPDF”, “qpdf”))
1. __Run a R CMD check on win-builder__   
    (devel and release versions) via ‘devtools::build_win()‘.
1. __Run a R CMD check on Ubuntu (via Travis-CI)__.
1. __Update ‘cran-comments.md‘__:
    1. Test environments,
    1. R CMD check results (explain ERRORs, WARNINGs, NOTEs).
    1. Downstream dependencies.
    1. Resubmit comments.
1. __Update ‘Version‘ field in the DESCRIPTION file__   
(major.minor.patch.dev).
1. __Update ‘Date‘ field in the DESCRIPTION file__.
1. __Update NEWS.md file__.
1. __Push all necessary commits to GitHub__.
1. __Run again a R CMD check locally just to be sure__.
    1. Use devtools::check().
1. __Push all necessary commits to GitHub__.
    1. Merge branches if necessary   
    Via GithHub website OR Via GIT: git merge –no-ff  branch_name
1. __Check vignettes__:
    1. Build your package sources
    1. Load them with:    
    install.packages(“../packageName_2.0.90002.tar.gz”,   
    repos = NULL, type = “source”)
    1. Use browseVignettes(“genderizeR”)
1. __Submit the package to CRAN__.
    1. Use devtools::release().
    1. Confirm  submission via link in the mail.
1. __Check results of submission__:
    1. in all CRAN checks    
    (from http://cran.r-project.org/web/packages)
    1. in comments inside the e-mail from CRAN
1. __Fix what needs to be fixed__.
    1. Consider increasing version number.
    1. Check everything again.
    1. Resubmit to CRAN.
1. __After successful submission__:
    1. Create a new release with tag version on GitHub repo.
        1. Copy and paste the contents of the relevant NEWS.md section into the release notes
    1. Increment the version of the package in the DESCRIPTION file (to X.X.X.9000).
    1. Promote your package
        1. Post on personal blog
        1. Post on Twitter (use #rstats)
        1. R-Bloggers
        1. etc.
1. __Update this checklist__.
    1. Update the checklist version number.
