---
title: "limeRick"
date: 2015-07-23T21:13:14-05:00
tags:  ["software","R"]
image_preview: ""
header: 
    image: ""
    caption: ""
summary: "The bridge between LimeSurvey and R."
external_link: ""
math: false
draft: false
---

# limeRick: The bridge between LimeSurvey and R

The R package LimeRick enables close connection between R and LimeSurvey - one of the most popular and advanced open-source scripts for on-line surveys (a.k.a. CAWI - Computer-Aided Web Interviewing). Using new LimeSurvey RemoteControl2 API for two-way data exchange the package allows for:

* importing on-line survey responses into R,
* adding new responses to the survey directly from R,
* automatically accessing surveys and question properties,
* implementing passive measurement surveys,
* developing data products based on real-time declarative data collection.

README, BugReports and development repository on GitHub:
<a href="https://github.com/kalimu/LimeRick">https://github.com/kalimu/LimeRick</a>

Presentation of early version of LimeRick package: http://rpubs.com/kalimu/erum

## Roadmap

* updating and expanding documentation of the package (man pages)
* checking available LimeSurvey updates via R
* ping function to an active survey
* function for populating survey with temporary lorem ipsum answers
* dedicated demo Shiny app
* getting only new responses
* automatically labelling survey questions in R
* generating a data frame of temporary responses
* unit testing
* tutorial vignette
* package on CRAN
* ~~first public package presentation on European R User Meeting in Poznań~~
