---
title: Cykl publikacji
author: Kamil Wais
date: '2017-06-26'
categories:
  - research
tags:
  - habilitacja
slug: cykl
draft: false
---
`r df = data.frame(lista = "A", punkty_min=0, punkty_max=0, published=0, stringsAsFactors = FALSE)`


## Nowe paradygmaty w metodach, technikach i narzędziach badań społecznych wykorzystujących technologie internetowe i dane otwarte.

> Non-linear On-line Micro-Surveys With Instant Feedback (NOMSIF) as New Approach to Respondent-Researcher Relationship





1. __LimeRick__. Analytical Data Products based on __Real-Time Declarative & Passive Data Collection__ 
`r article = c(lista = "A", punkty_min=30, punkty_max=50, published=0); df = rbind(df, article); paste0("[", article, "]")`

1. Process analysis of on-line surveys __paradata__. IMID.
`r article = c(lista = "A", punkty_min=20, punkty_max=30, published=0); df = rbind(df, article); paste0("[", article, "]")`

1. The Impact of Traditional __Researcher-Respondent Relationship__ Paradigm on Response-Rates. __NetLogo__ 
`r article = c(lista = "A", punkty_min=20, punkty_max=50, published=0); paste0("[", article, "]")`
`r df = rbind(df, article)`

1. On-line Surveys with Instant Feedback (__OSIF__) as a New Paradigm in Social Science Research Techniques.
`r article = c(lista = "A", punkty_min=20, punkty_max=50, published=0); paste0("[", article, "]")`
`r df = rbind(df, article)`

1. Securing __Sensitive Data in On-line Surveys & Data Products__ with Asymmetric Cryptography. 
`r article = c(lista = "A", punkty_min=20, punkty_max=50, published=0); paste0("[", article, "]")`
`r df = rbind(df, article)`


1. ~~__GenderizeR__~~ 
~~`r article = c(lista = "A", punkty_min=30, punkty_max=30, published=30); paste0("[", article, "]")`~~
`r df = rbind(df, article)`

1. GUS: __Closed Open Data__. Case study of Poland.
`r article = c(lista = "A", punkty_min=10, punkty_max=40, published=0); paste0("[", article, "]")`
`r df = rbind(df, article)`

1. __DataScience in H&SS__. 
`r article = c(lista = "A", punkty_min=10, punkty_max=50, published=0); paste0("[", article, "]")`
`r df = rbind(df, article)`

1. __Krajowy Panel Badawczy__
`r article = c(lista = "B", punkty_min=10, punkty_max=15, published=0); paste0("[", article, "]")`
`r df = rbind(df, article)`


```{r, echo=FALSE}
suppressPackageStartupMessages(library(dplyr))
tab = df %>% group_by(lista) %>% 
    summarize(punktyMin = sum(as.numeric(punkty_min)), 
              punktyMax = sum(as.numeric(punkty_max)),
              opublikowane = sum(as.numeric(published))
              )
pander::pander(tab)
```

<!--
## Temp

### Recruitment of Respondents & Panelists:
1. The Impact of __Traditional Researcher-Respondent Paradigm__ on Response-Rates.    
1. Effectiveness of __Panelist Driven Recruitment__ for On-line Access Panels. Results from Agent-Based Modeling Simulations.  
1. Effectiveness of __On-line Recruitments Methods__ for On-line Access Panels. Results from Empirical Study.

### New Paradgim:
1. Non-Linear On-line Micro-Surveys with Instant Feedback __(NOMSIF) as a New Paradigm__ in Social Science Research Techniques.  

### Respondent & Feedback Data:
1. Securing __Sensitive Data__ in On-line Data Products based on Real-Time On-line Surveys with Asymmetric Cryptography.  
1. External sources for question feedbacks. Problems with Research & Administrative __Open Data__.

### Respondent Long-Term Engagement:
1. Towards the __Standards of Paradata Analysis__ in On-line Surveys.

1. Towards __New Standards of Paradata Analysis__ in On-line Surveys.
`r article = c(lista = "A", punkty_min=20, punkty_max=30); paste0("[", article, "]")`
`r df = rbind(df, article)`

1. Collecting and Analysing __Paradata in Non-Linear On-line Surveys__.  
1. The Use of __Gammification based on Paradata__ in Non-Linear On-line Surveys.  
1. Real-Time A/B Testing and __Question Evaluation__ in On-line Micro-Surveys with Instant Feedback.  
1. Analysis of __Life Cycle of Panelists__ in Non-Linear On-line Access Panel based on  Micro-Surveys with Instant Feedback Model.
-->
